### ISSUE TITLE
Merge query constraints with window, space and display selectors

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#112]
### Discussion

The query syntax supports optional constraints for querying only a specified window, space or display. These constraints are `arrangement index` for displays, `mission-control index` for spaces and `window id` for windows.

The display, space and window commands, however, do not support these, but rather a set of selectors named `DISPLAY_SEL`, `SPACE_SEL`, and `WINDOW_SEL` instead. 

A third case are the window commands, which support specifying an optional `window id` for specifying the window to act on, defaulting to the focused display. 

Some Initial discussion about this was in https://github.com/koekeishiya/yabai/issues/104#issuecomment-509681448, but I think this is worth moving into its own thread to both discuss and track the issue, and also to let #104 be about the display boundary issue.

### Feature request

- Accept arrangement indices as a valid display selector, mission-control indices as valid space selectors and window ids as valid window selectors. 
- Simplify the user-facing syntax (and reuse code?) by accepting selectors everywhere.
- Allow an optional space and display selector for space and display commands to specify which space or display to act on for consistency.

**Comment by koekeishiya** [comment]
I'm not opposed to this, but there are some caveats to address. Some combinations make sense while others don't.

```
# this makes sense
yabai -m window first --swap east

# window 123 is on space 3, currently not visible - this does not make sense
yabai -m window first --swap 123

# 123 is the same window as above - this makes sense
yabai -m window --focus 123

# this also makes sense
yabai -m query --windows --window 123
```

There may be other caveats to address as well.

**Comment by dominiklohmann** [comment]
> ```sh
> # window 123 is on space 3, currently not visible - this does not make sense
> yabai -m window first --swap 123
> ```

I think the above should be allowed. It does make sense to me: Swap the first window on the focused space with the window 123 (on space 3). yabai can already pull windows from other spaces when using `yabai -m window 123 --space 1` without space 3 being active.

Some other thoughts:

- Warping a floating window on a tiled window needs to unfloat it
- Warping a window on a floating window is impossible
- Swapping windows should needs to swap their floating attribute

**Comment by koekeishiya** [comment]
> The new addition would actually be yabai -m query --windows --window first.

As long as this means the same as it would in a `yabai -m window --focus first` context, I am fine with that. That query statement would return information about the first window in tree if ran in a bsp-space. Not information about the *first* window known to *yabai*.

I agree that unifying selectors is a good change. As for the impact all these various combinations will bring, I need to see during implementation whether things make sense or not.

**Comment by koekeishiya** [comment]
Reworked the message parser to support the following:

- Accept arrangement indices as a valid display selector, mission-control indices as valid space selectors and window ids as valid window selectors.
- Simplify the user-facing syntax (and reuse code?) by accepting selectors everywhere.
- Allow an optional space and display selector for space and display commands to specify which space or display to act on for consistency.

Note that only the parsing has been implemented so far. Combinations that are *natural* will work immediately, where as commands that require special handling (e.g swapping or warping windows across spaces) etc will be handled at a later time.

**Comment by dominiklohmann** [comment]
This already feels both powerful and simpler to use. I think stuff like https://github.com/koekeishiya/yabai/issues/113#issuecomment-510670144 really shows this.

**Comment by koekeishiya** [comment]
@dominiklohmann 

Would you be able to test the multi-display functionality related to space commands and display commands, as well as the updated *DISPLAY_SEL* ? I'm not at home and don't have the opportunity to test on multiple displays for quite some time.

**Comment by dominiklohmann** [comment]
Will test thoroughly over the next few days and report back. Multi-display tests early on tomorrow. I assume there'll be lots of small things with this many code changes.

**Comment by koekeishiya** [comment]
> Will test thoroughly over the next few days and report back.

Great, thank you!

Kinda off topic, but I really like how the design has made *yabai* way more scriptable by the end user, compared to any other window manager (that I know of) on macOS thus far.

**Comment by dominiklohmann** [comment]
There needs to be some sort of plan for addressing native-fullscreen spaces. Currently, their arrangement indices are all 0 and as such they cannot be addressed. 

I thought about giving them a prefix, but that'd break the json format. There's a hard limit of macOS spaces, so maybe numbering should start after that?

**Comment by koekeishiya** [comment]
> There's a hard limit of macOS spaces, so maybe numbering should start after that?

I have never tried to operate with more than 16spaces for a substantial amount of time, however I know that using the scripting-addition I have successfully had at least 35 spaces on a single display, all working.

**Comment by dominiklohmann** [comment]
## Multi-display test observations

These are my initial observations after like 1.5 hours of testing all sorts of things. There's just too many combinations, so that's it for today. Tried to sort them somehow.

Generally I'm pretty happy with how easy it is to reason about commands now. There are barely any side effects to consider or internal limitations now. 

### Window commands

- `window --display`
  - [x] Moving windows from and to focused, active and inactive spaces works across multiple displays
  - [ ] Moving windows unnecessarily focuses windows
- `window --space`
  - [x] Moving windows works as expected from and to focused, active and inactive spaces
  - [ ] When moving windows to an inactive space on an different monitor, they do not get tiled properly until the space is active (they get resized, but not moved)
- `window --focus`
  - [x] Works as expected
- `window --warp`
  - [ ] Does not work across display boundaries
  - [ ] Does not work across space boundaries
- `window --swap`
  - [ ] Does not work across display boundaries
  - [ ] Does not work across space boundaries
- `window --insert`
  - [x] Works as expected (I think? I never use this tbh)
- `window --toggle float|sticky|split|border|zoom-parent|zoom-fullscreen`
  - [x] Works as expected
- `window --toggle native-fullscreen`
  - [x] Works as expected
  - [ ] When you return windows from native-fullscreen, they do not return to their original space, but to the active space on that display instead

I still need to test `window --move|--resize|--grid` and will get to them later on.

### Space commands

- `space --focus`
  - [x] Works as expected
- `space --create`
  - [x] Works as expected
- `space --destroy`
  - [ ] **Crash:** I used `yabai -m space 4 --create` to create space 6 on display 2. Before this, space 6 was the only space on display 3, but this had now been moved to be space 7. Running `yabai -m space 6 --destroy` caused the Dock to crash. The crash log can be expanded at the very bottom of this comment.
  - [x] Other than that it... works? Didn't get it to crash other than that one time and I cannot reproduce it either.
- `space --move`
  - [x] Works as expected
- `space --display`
  - [x] Works as expected
  - [ ] **Bug:** When doing this using mission control instead of yabai, yabai fails to check whether the dimensions of the displays are different
- `space --balance|--mirror|--rotate|--padding|--gap|--toggle|--layout`
  - [x] Works as expected

### Display commands

Nothing changed here as far as I can tell. The optional display selector may only come into play for future commands, as `--focus` does not care about the source display.

### Crash logs

<details>
<summary>"Dock quit unexpectedly while using the payload plug-in"</summary>

```
Process:               Dock [77977]
Path:                  /System/Library/CoreServices/Dock.app/Contents/MacOS/Dock
Identifier:            com.apple.dock
Version:               1.8 (2019.1)
Build Info:            Dock-2019001000000000~1
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Dock [77977]
User ID:               501

PlugIn Path:             /Library/ScriptingAdditions/yabai.osax/Contents/Resources/payload.bundle/Contents/MacOS/payload
PlugIn Identifier:       com.koekeishiya.yabai-sa
PlugIn Version:          1.0 (1)

Date/Time:             2019-07-12 08:49:46.633 +0200
OS Version:            Mac OS X 10.15 (19A501i)
Report Version:        12
Bridge OS Version:     4.0 (17P50496d)
Anonymous UUID:        7754B96D-2B03-57AE-9A3B-249F859121FE

Sleep/Wake UUID:       C43B8EF9-4A91-4992-B89C-CBF4996C49DC

Time Awake Since Boot: 110000 seconds
Time Since Wake:       4300 seconds

System Integrity Protection: disabled

Crashed Thread:        2

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000028
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [77977]

VM Regions Near 0x28:
--> 
    __TEXT                 00000001000db000-00000001000de000 [   12K] r-x/r-x SM=COW  /System/Library/CoreServices/Dock.app/Contents/MacOS/Dock

Application Specific Information:
dyld3 mode

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff6aa9d396 mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6aa9d8fc mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff33324a99 __CFRunLoopServiceMachPort + 322
3   com.apple.CoreFoundation      	0x00007fff33324035 __CFRunLoopRun + 1695
4   com.apple.CoreFoundation      	0x00007fff33323711 CFRunLoopRunSpecific + 499
5   com.apple.dock                	0x000000010023f228 0x1000db000 + 1458728
6   com.apple.dock                	0x000000010023f0de 0x1000db000 + 1458398
7   libswiftObjectiveC.dylib      	0x00007fff6a60ef0e autoreleasepool<A>(invoking:) + 46
8   com.apple.dock                	0x000000010023f12d 0x1000db000 + 1458477
9   com.apple.dock                	0x000000010023f0be 0x1000db000 + 1458366
10  libswiftObjectiveC.dylib      	0x00007fff6a60ef0e autoreleasepool<A>(invoking:) + 46
11  com.apple.dock                	0x00000001000e0768 0x1000db000 + 22376
12  libdyld.dylib                 	0x00007fff6a954c49 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff6aaa0b46 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6ab610b4 _pthread_cond_wait + 701
2   com.apple.dock                	0x00000001000f98d2 0x1000db000 + 125138
3   libsystem_pthread.dylib       	0x00007fff6ab60daa _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff6ab5d6af thread_start + 15

Thread 2 Crashed:
0   com.apple.dock                	0x0000000100322ccb 0x1000db000 + 2391243
1   libswiftCore.dylib            	0x00007fff69e3a400 __ContiguousArrayStorageBase.__allocating_init() + 32
2   com.apple.dock                	0x0000000100418e81 0x1000db000 + 3399297
3   com.koekeishiya.yabai-sa      	0x0000000103367f75 handle_connection + 4181
4   libsystem_pthread.dylib       	0x00007fff6ab60daa _pthread_start + 125
5   libsystem_pthread.dylib       	0x00007fff6ab5d6af thread_start + 15

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff6ab5d68c start_wqthread + 0

Thread 2 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00fffffffffffff8  rcx: 0x000000000000025d  rdx: 0x0000600002dda940
  rdi: 0x00006000037feb20  rsi: 0x0000000000000000  rbp: 0x0000700007718820  rsp: 0x00007000077187e0
   r8: 0x000000000000025d   r9: 0x0000000100536ed0  r10: 0x00007fff972e7768  r11: 0x00007fff69f79be0
  r12: 0x0000000000000003  r13: 0x0000000000000000  r14: 0x00007fff7467ab13  r15: 0x000000000000025d
  rip: 0x0000000100322ccb  rfl: 0x0000000000010202  cr2: 0x0000000000000028
  
Logical CPU:     4
Error Code:      0x00000004 (no mapping for user data write)
Trap Number:     14
```

</details>

**Comment by koekeishiya** [comment]
> Crash: I used yabai -m space 4 --create to create space 6 on display 2. Before this, space 6 was the only space on display 3, but this had now been moved to be space 7. Running yabai -m space 6 --destroy caused the Dock to crash. The crash log can be expanded at the very bottom of this comment.

This should now be fixed on the latest master (new version of the scripting-addition). My assumption is that this piece of code needs to be ran from the main-thread.

> Nothing changed here as far as I can tell. The optional display selector may only come into play for future commands, as --focus does not care about the source display.

There is no practical reason for this, but you can do the following:
```
# in a 3-display setup, make the first display be your focused one.
# this will focus display 3, not display 2.
yabai -m display next --focus next
```

 If the selector for the *acting* entity is not specified, it will act on the focused entity of that type. If the selector is specified, but it is a *relative* selector such as prev, next, directional or whatever is available - it will use the focused entity of that type as its base. This is mostly because I found that to be more consistent behaviour instead of disallowing various options of the selector.

This holds true for displays, spaces and window selectors. Let me know if you think this should be changed to not be possible - takes like 5 seconds.

> When doing this using mission control instead of yabai, yabai fails to check whether the dimensions of the displays are different

Not sure I understand what you are saying here. Is it that when a space is moved to another display through the built-in mission-control mechanism that the windows are not updated? If so, does a `yabai -m space --toggle padding` fix it, or is it just forever broken ?

> When you return windows from native-fullscreen, they do not return to their original space, but to the active space on that display instead

I remember running into some trouble regarding this when I implemented the window rules, but I don't recall the exact behaviour at this point.

> When moving windows to an inactive space on an different monitor, they do not get tiled properly until the space is active (they get resized, but not moved)

> Moving windows unnecessarily focuses windows

These two issues are hard for me to reason about without having access to multiple displays myself. They should work properly at the moment, if the system behaved the way I expected.

Thanks for the extensive testing, although there are less bugs than I initially expected there to be. Maybe some more will be revealed as time passes.

**Comment by dominiklohmann** [comment]
> This holds true for displays, spaces and window selectors. Let me know if you think this should be changed to not be possible - takes like 5 seconds.

Nah, all good. I don't see any downsides tbh.

> Not sure I understand what you are saying here. Is it that when a space is moved to another display through the built-in mission-control mechanism that the windows are not updated? If so, does a `yabai -m space --toggle padding` fix it, or is it just forever broken ?

It's broken until I restart yabai or move the space back using Mission Control. Yabai can't even tile windows on the space, it moves them back to the old display. I will factor this out into another issue I think.

> > When you return windows from native-fullscreen, they do not return to their original space, but to the active space on that display instead
> 
> I remember running into some trouble regarding this when I implemented the window rules, but I don't recall the exact behaviour at this point.

#27 I believe.

> These two issues are hard for me to reason about without having access to multiple displays myself. They should work properly at the moment, if the system behaved the way I expected.
> 
> Thanks for the extensive testing, although there are less bugs than I initially expected there to be. Maybe some more will be revealed as time passes.

Just wait until the Emacs users check this feature out. They always find their weird issue. 🤷‍♂

**Comment by koekeishiya** [comment]
window *swap* and *warp* commands should now work across space/display boundaries for *managed/tiled* windows. I don't think I want to extend this to work with floating windows as a part of this issue, but that should potentially be tackled at a later point.

**Comment by koekeishiya** [comment]
> window --display
 >>Moving windows unnecessarily focuses windows

This issue should now be resolved. There is code on purpose to retain focus if the window that is moved to a different space/display is on the active space of its display. This check needed to also check if the window that is moved is the focused window. This was put in place to fix #37.

**Comment by dominiklohmann** [comment]
Seems to work fine, except for one reproducible weirdness. When I warp a window to my secondary display, which is right above the main one (see third screenshot), the warped window is larger than it should be towards the bottom side only.

![image](https://user-images.githubusercontent.com/4488655/61156276-400b4780-a4f3-11e9-8ee3-894f3574db1a.png)

![image](https://user-images.githubusercontent.com/4488655/61156304-544f4480-a4f3-11e9-9e20-22f3d9a1936b.png)

![image](https://user-images.githubusercontent.com/4488655/61156612-1868af00-a4f4-11e9-9cf0-85d37f9cb558.png)

**Comment by dominiklohmann** [comment]
> This issue should now be resolved. There is code on purpose to retain focus if the window that is moved to a different space/display is on the active space of its display. This check needed to also check if the window that is moved is the focused window. This was put in place to fix #37.

Found a bug with this. 

When I move the focused window on the active space of display A to display B, and as a result the desktop is focused, ffm will not work on the same window until another window was focused. I assume ffm does some caching here which is not reset when the desktop is focused.

**Comment by koekeishiya** [comment]
> I assume ffm does some caching here which is not reset when the desktop is focused.

Correct. Fixed on master.

**Comment by dominiklohmann** [comment]
This does not appear to be fixed. Can reproduce 100% with the same steps I explained above.

```sh
# sanity check: version 
$ brew info --json koekeishiya/formulae/yabai | jq '.[0].installed[0].version'
"HEAD-16561a9"

# sanity check: ffm
$ yabai -m config focus_follows_mouse
autofocus

# only and focused window on display 1 is iTerm2, only window on display 2 is Chrome
$ yabai -m window --display 2

# now the desktop is focused
# ffm does not work on the same iTerm2 window without hovering the Chrome window to its left first

**Comment by koekeishiya** [comment]
It should actually be fixed this time for real. Forgot about the other cache, heh.

**Comment by dominiklohmann** [comment]
Can confirm. 👍

**Comment by koekeishiya** [comment]
> Seems to work fine, except for one reproducible weirdness. When I warp a window to my secondary display, which is right above the main one (see third screenshot), the warped window is larger than it should be towards the bottom side only.

This should be fixed on master. I believe the issue was that I incorrectly set the windows size to the size of the new node, and then we told macOS to move the space - which caused macOS to compare resolutions and upscale the windows size when it was moved.

> When you return windows from native-fullscreen, they do not return to their original space, but to the active space on that display instead

I have no idea how this can be solved in a robust and clean manner. This is probably something that we just have to document and live with.

> When moving windows to an inactive space on an different monitor, they do not get tiled properly until the space is active (they get resized, but not moved)

If I understand you correctly, the window does automatically get the correct position/size when that space is activated, yes? I had similar issues where sometimes a window on an inactive space will update fine, and sometimes they won't - no pattern really.. I notice this mostly when adjusting the display resolution or disconnecting a display. As long as the window does get the correct dimensions upon space activation I probably won't bother looking into this.

**Comment by dominiklohmann** [comment]
> This should be fixed on master. I believe the issue was that I incorrectly set the windows size to the size of the new node, and then told macOS to move to the new space - which caused macOS to compare resolutions and upscale the windows size when it was moved.

It's not fixed. Window still gets increased in size to the bottom and right side. 

> > When you return windows from native-fullscreen, they do not return to their original space, but to the active space on that display instead
> 
> I have no idea how this can be solved in a robust and clean manner. This is probably something that we just have to document and live with.

Can you focus the window before making it native-fullscreen? Toggling native-fullscreen focuses it anyways, and focusing it manually before that makes it so the recent space is set properly, which will make it return to the proper space.

> If I understand you correctly, the window does automatically get the correct position/size when that space is activated, yes? [...] As long as the window does get the correct dimensions upon space activation I probably won't bother looking into this.

Fair enough. It's no big deal I think.

**Comment by koekeishiya** [comment]
> It's not fixed. Window still gets increased in size to the bottom and right side.

Hmm weird.

> Can you focus the window before making it native-fullscreen? Toggling native-fullscreen focuses it anyways, and focusing it manually before that makes it so the recent space is set properly, which will make it return to the proper space.

Implemented on master. Does this solve the issue?

**Comment by dominiklohmann** [comment]
> Implemented on master. Does this solve the issue?

It does not. This appears to be a timing issue, so maybe you need to wait for the space to be changed.

```sh
# this does not work:
yabai -m window --focus 87165 && yabai -m window 87165 --toggle native-fullscreen

# this does work:
yabai -m window --focus 87165 && sleep 0.1 && yabai -m window 87165 --toggle native-fullscreen
```

**Comment by koekeishiya** [comment]
> This appears to be a timing issue, so maybe you need to wait for the space to be changed

Implemented waiting for space change on master. Appears to work, but did not test it extensively.

**Comment by dominiklohmann** [comment]
Can confirm it works.

That should be it for this issue, right? Very happy with how all this turned out.

**Comment by koekeishiya** [comment]
I think that’s it, yeah.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
