### ISSUE TITLE
`window --focus <east|west>` not working on screens with misaligned `y`

### ISSUE THREAD

**Issue by brorbw** [koekeishiya/yabai#1463]
Expected:
```sh
➜ yabai -m window --focus east
could not locate a eastward managed window.
```
What I got is that it selects the window below on the screen. This behaviour has changed since the previous version and it means that my navigation don't work
```sh
alt - h: yabai -m window --focus west  || (yabai -m display --focus west  && yabai -m window --focus east)
alt - j: yabai -m window --focus south || (yabai -m display --focus south && yabai -m window --focus north)
alt - k: yabai -m window --focus north || (yabai -m display --focus north && yabai -m window --focus south)
alt - l: yabai -m window --focus east  || (yabai -m display --focus east  && yabai -m window --focus west)
```

**Comment by brorbw** [comment]
Video of behaviour
https://user-images.githubusercontent.com/5909562/192783367-34e2f2e8-640c-4779-b369-0efbb71e5769.mov

**Comment by brorbw** [comment]
I did a little more digging and found that this placement of displays does not work
![309128585_3426542004337344_7684211690507396868_n](https://user-images.githubusercontent.com/5909562/192784997-8ff903be-65f9-454d-a928-6f39b0213b6d.png)
But this does
![309463893_626282548901714_5614346904078961827_n](https://user-images.githubusercontent.com/5909562/192785269-ca50b662-c3a5-4ddb-bdad-a9eb0a69d234.png)

**Comment by DonaldoSoWell** [comment]
Hi there, I have the same issue with two screens side by side in landscape mode. 

The expected behaviour can be reached by the placement of displays hack (aligning them on top) as suggested by @brorbw.

I go with this hack but moving the mouse from one display to the other fells tricky with this placement

Is a fix planned for the issue ?

**Comment by brorbw** [comment]
>I go with this hack but moving the mouse from one display to the other fells tricky with this placement

Tell me about it. It's not really usable but I see no alternative

**Comment by brorbw** [comment]
Any update on this?

**Comment by brorbw** [comment]
I have now turned my monitors to landscape mode, not related to yabai. Configuration can be seen below. 
![Screenshot 2023-02-10 at 00 42 06](https://user-images.githubusercontent.com/5909562/217963679-29be1986-6f69-47c5-92f2-80a9e180aef8.png)

The problem still exists. When I have a 2:1 configuration on my leftmost screen, and ONLY with a 2:1 configuration yabai detects a window to the right of my rightmost window. I cannot for the life of me figure out why.

![Screenshot 2023-02-10 at 00 41 40](https://user-images.githubusercontent.com/5909562/217964112-4f14e5b5-5d58-429a-a847-f2f722e3fb0d.png)

**Comment by brorbw** [comment]
Are there any updates?

**Comment by brorbw** [comment]
I have found a new scenario
For the left most monitor of three all with the same resolution
https://user-images.githubusercontent.com/5909562/235494004-ad543f0c-0b2d-4324-b725-9392688388bd.mov

**Comment by koekeishiya** [comment]
I was only able to reproduce the the issue mentioned in this comment, which is now resolved on master: https://github.com/koekeishiya/yabai/issues/1463#issuecomment-1424986203

Not sure if the other issus mentioned were caused by the same underlying issue, or if they are separate.

**Comment by koekeishiya** [comment]
Probably fixed in v5.0.5. Feel free to reopen if you can reproduce the issue in the new version.

**Comment by brorbw** [comment]
Problem still persist on the leftmost screen when using three screens.
https://github.com/koekeishiya/yabai/assets/5909562/9f4e4ff7-cee2-4f62-8f4c-5bf906462f97

**Comment by offeex** [comment]
have the same issue:

```
offeex@MacBookPro ~> yabai -m window --focus east
could not locate a eastward managed window.
```

tho, i'm using managed layout. Any workaround?

**Comment by tim-morriss** [comment]
I'm having the same issue as well, I have two monitors in landscape mode side-by-side:

```
[{
	"id":6,
	"uuid":"ACDEDE54-0AE9-4C77-BB43-8405BB1AD95E",
	"index":1,
	"label":"",
	"frame":{
		"x":0.0000,
		"y":0.0000,
		"w":2560.0000,
		"h":1440.0000
	},
	"spaces":[1, 2, 3, 4, 5],
	"has-focus":true
},{
	"id":7,
	"uuid":"06A2F1AE-112D-4766-A53D-A8C754089A3B",
	"index":2,
	"label":"",
	"frame":{
		"x":2560.0000,
		"y":0.0000,
		"w":1920.0000,
		"h":1080.0000
	},
	"spaces":[6, 7, 8, 9],
	"has-focus":false
}]
```
