### ISSUE TITLE
yabai -m space --focus does not do anything

### ISSUE THREAD

**Issue by Aleppi** [koekeishiya/yabai#1519]
Whenever I execute `yabai -m space --focus next` nothing happens, and I get no output in the terminal. I have disabled SIP and installed the scripting addition, but it still does not work. Everything was working until I updated yabai to the latest HEAD yesterday. Everything else still works, except for focusing spaces. I am on MacOS 12.4.

**Comment by manucalop** [comment]
Does it work after `sudo yabai --load-sa`?

**Comment by Aleppi** [comment]
> Does it work after `sudo yabai --load-sa`?

Nope, that makes no difference.

**Comment by usmajeed** [comment]
Same issue

**Comment by prdanelli** [comment]
Since updating to Ventura, `yabai -m space --focus 2` doesn't work for me. Updating to the latest `HEAD` build gives me issues with yabai constantly trying to get permission within Security Preferences.

**Comment by Serralq** [comment]
I also have the same issue with 12.3 MacOS, SIP disabled, script additions added on,and both 5.0.1 version or the HEAD version. I've got window opacity and topmost to work so I'm sure what I stated above to be correct. A workaround until the issue is closed is to  use the System Preferences > Keyboard > Shortcuts > Mission Control hotkeys.

**Comment by Ermaolaoye233** [comment]
Same issue on Ventura 13.0.1

**Comment by pigmej** [comment]
I have the same issue starting today the only change that I made was to upgrade to Ventura. No errors what so ever.

**Comment by pigmej** [comment]
What I have noticed though is one behaviour.

I have workspaces 1-4 on first monitor, and 5-8 on second.

Whenever I `yabai -m space --focus x` and if X is belonging  to the other monitor then it basically switches the monitors (focus follows it)
So when I'm on workspace 5 and I `focus` `1` then focus switches to the other monitor, BUT the workspace is unchanged there.

**Comment by mefengl** [comment]
delete them in `skhdrc`, just use the system setting in

![image](https://user-images.githubusercontent.com/71683364/203795054-abf9a459-7d5e-4c80-a677-db3839e839b8.png)

you probably see only two options here, that because you now only have one space.
create 10 spaces, and then open this setting again, you shall see them all.

how to create 10 spaces since yabei does not work? well, 
![image](https://user-images.githubusercontent.com/71683364/203795903-8c4ce5ed-8359-4817-92fe-38706fbb4808.png)
there fingers up in the trackpad or other way you know, then you shall see the + button in the left up corner

**Comment by pigmej** [comment]
Would work for me, but "sadly" I made a script that numbers spaces on screens from 1 because that's the setup that I'm used to.

Anyway, the proposed workaround is a workaround indeed for a standard workflow.

**Comment by 24unix** [comment]
> or,  there fingers up in the trackpad or other way you know, then you shall see the + button in the right up corner
ctrl. - up arrow (cursor key) should work, too.

But: You are limited to 16 Shortcuts in macOS, so for me the feature is useless (3 displays with 9 spaces each).

**Comment by mefengl** [comment]
> > or,  there fingers up in the trackpad or other way you know, then you shall see the + button in the right up corner
> > ctrl. - up arrow (cursor key) should work, too.
> 
> But: You are limited to 16 Shortcuts in macOS, so for me the feature is useless (3 displays with 9 spaces each).

so curious about how to work with 27 screens...

**Comment by 24unix** [comment]
> so curious about how to work with 27 screens...
I see each combo of three display as one desktop.
So 9 desktops.

One main desktop.
One for XCode.
One for DevOps.
One for PHP … and so on.

Everybody has a different workflow.

**Comment by timhradil** [comment]
> Whenever I execute `yabai -m space --focus next` nothing happens, and I get no output in the terminal. I have disabled SIP and installed the scripting addition, but it still does not work. Everything was working until I updated yabai to the latest HEAD yesterday. Everything else still works, except for focusing spaces. I am on MacOS 12.4.

This is because the latest commit fixes an issue with focusing spaces in OS 13. Unfortunately, due to a change in script injection in Ventura, this is a breaking change and you will need to upgrade to 13.x to focus on other spaces with the latest and future commits. To make yabai work on 12.4 you will have to downgrade to a previous commit.

**Comment by timhradil** [comment]
> Since updating to Ventura, `yabai -m space --focus 2` doesn't work for me. Updating to the latest `HEAD` build gives me issues with yabai constantly trying to get permission within Security Preferences.

When using HEAD, you need to add yabai to the accessibility permissions manually. To do this click the plus in the bottom left of Accessibility list in the Security Preferences pane then find yabai in finder. I found my yabai at this path: /opt/homebrew/Cellar/yabai/HEAD-206c0d6/bin/yabai. Rather than at /usr/local/bin/yabai as noted in the wiki.

**Comment by prdanelli** [comment]
>I found my yabai at this path: /opt/homebrew/Cellar/yabai/HEAD-206c0d6/bin/yabai. 

@timhradil Thank you for your reply. I tried this and I am still getting the persistent Security & Privacy popups when using the latest `--HEAD` version.

**Comment by szaffarano** [comment]
@prdanelli try running
```sh
echo "$(brew --prefix yabai)/bin/yabai"
```
It prints the binary used by the brew service, and hence the one you have to grant accessibility permissions.

**Comment by prdanelli** [comment]
Thanks @szaffarano. After installing `--HEAD`, I get the following: 

```sh
/🔒 
❯ which yabai
/opt/homebrew/bin/yabai

/🔒 
❯ ls -la /opt/homebrew/bin/yabai
lrwxr-xr-x 38 paul  3 Dec 10:46 /opt/homebrew/bin/yabai -> ../Cellar/yabai/HEAD-206c0d6/bin/yabai
```

Adding that binary to the Accessibility options, I still get the constant popup trying to open Security and Privacy options.

**Comment by szaffarano** [comment]
Did you run the command I listed above? In my environment:
```sh
❯ echo "$(brew --prefix yabai)/bin/yabai"
/opt/homebrew/opt/yabai/bin/yabai
```
and on the other hand:
```
❯ pgrep -lfa yabai     
85444 /opt/homebrew/opt/yabai/bin/yabai
```
In other words, although I also have the symlink `opt/homebrew/bin/yabai` pointing to the same location as you have, the binary used by brew services is `/opt/homebrew/opt/yabai/bin/yabai`

**Comment by prdanelli** [comment]
@szaffarano I tried adding both the bin and the simlink to the bin. 

Nothing I seem to do works and all focus commands are still broken since 5.0.was released.

**Comment by szaffarano** [comment]
@prdanelli by `the bin` do you mean the output of `echo "$(brew --prefix yabai)/bin/yabai"`
again, `which yabai` returns a different binary, at least in my environment:
```sh
❯ which yabai
/opt/homebrew/bin/yabai

❯ echo "$(brew --prefix yabai)/bin/yabai"
/opt/homebrew/opt/yabai/bin/yabai

❯ ls -l /opt/homebrew/bin/yabai                                                                                    
Dec  3 07:32 /opt/homebrew/bin/yabai -> ../Cellar/yabai/HEAD-206c0d6/bin/yabai

❯ ls -l /opt/homebrew/opt/yabai/bin/yabai                                                                          
Dec  3 07:44 /opt/homebrew/opt/yabai/bin/yabai
```
I removed all the `yabai` binaries from `Privacy & Security -> Accessibility` config except `/opt/homebrew/opt/yabai/bin/yabai`

**Comment by guanyilun** [comment]
@prdanelli I'm experiencing the same problem on 12.6. I created a new issue for this. I fixed it by downgrading `OSAX_VERSION` to 2.0.15. Hope this is helpful while waiting for an official fix.

**Comment by koekeishiya** [comment]
Fixed in. https://github.com/koekeishiya/yabai/commit/c02de22e0c7c653d2048fd15eb1f86677d0f43e5 #1549

**Comment by nagy135** [comment]
is this not included  in the latest release?  I m running 5.0.2 that was released hour ago and this still doesnt work for me

**Comment by koekeishiya** [comment]
Works fine for me; read this comment for instructions on how to debug your setup: https://github.com/koekeishiya/yabai/issues/1515#issuecomment-1344070256

**Comment by nagy135** [comment]
you are correct, so just `pkill Dock` => `sudo yabai --load-sa` was it for me
