### ISSUE TITLE
window_destroyed signal fires before window is removed

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#154]
### Bug report

The `event=window_destroyed` signal is unreliable, as querying windows from it may or may not include the destroyed window.

This bug has been haunting me for weeks now, making me question my sanity and why signals were unreliable sometimes. I think I've found the root cause:

The signal is transmitted asynchronously before the event is processed internally by yabai.  The actual handling of the event happens in the `event_destroy` function, which is called after `event_signal_transmit`.

https://github.com/koekeishiya/yabai/blob/b3eb9d156ee2f47c92c4d588904fc03f11e847ed/src/event_loop.c#L60-L66

**Comment by koekeishiya** [comment]
I don't see a clean solution to this problem as long as the window_destroyed signal transmits both the window id and the window pid.

**Comment by dominiklohmann** [comment]
Let's rephrase the question then: Iff `window_destroyed`, `application_terminated` and `display_removed` signals were not carrying any arguments, could this issue be resolved?

This might break some scripts that rely on `argc=$#` or `pid=$1`, but other than that the data was mostly unusable in practice anyways for these signals.

**Comment by koekeishiya** [comment]
`application_terminated` and `display_removed` doesn't have this problem. I can solve this issue and have `window_destroyed` pass the *window id*, just not the *application pid*.

**Comment by dominiklohmann** [comment]
I've been wondering whether including the pid is necessary anyways. I've only needed to use it once, but I can get it from the wid anyways with a simple query.

pid="$(yabai -m query --windows --window "${wid}") | jq -r '.pid'"

**Comment by koekeishiya** [comment]
Note that that query will not work after in your handler for the *window_destroyed* script.

**Comment by dominiklohmann** [comment]
Yeah, that was for all queries. The pid seems useless outside of the `application_*` events.

**Comment by koekeishiya** [comment]
Should we just remove the pid from all window_* signals to be consistent?

**Comment by dominiklohmann** [comment]
That's a breaking change as it shifts $2 to $1. I'm all for it though. Better break now than later.

**Comment by koekeishiya** [comment]
Fixed on master.

**Comment by dominiklohmann** [comment]
Two small things:
- `window_created` still passed the pid, you only changed the docs for it.
- The ordering issue isn't fixed for `window_destroyed`, right? Just asking because I don't see it reflected in the code and the issue is labeled *addressed not released* already.

**Comment by koekeishiya** [comment]
> window_created still passed the pid, you only changed the docs for it.

Thanks for catching that, I was under the impression all window event had their args populated in the same codepath.

> The ordering issue isn't fixed for window_destroyed, right?

It's fixed, yes. Windows are now destroyed when the event is handled, before the signal is emitted.
