### ISSUE TITLE
Yabai and Arc Browser PiP weird interaction 

### ISSUE THREAD

**Issue by DylanMartin0930** [koekeishiya/yabai#1669]
I use Arc browser and it has a built in PiP window whenever you swap tabs while a video is running. Whenever i click on the PiP window to focus on it and use the playback buttons, yabai snaps my cursor to the bottom left corner of my screen. Im certain its yabai interacting with the PiP window as this doesnt happen when i have it disabled. I turned management off for the browser and it still does it. Any idea on how to fix this?

**Comment by azinsharaf** [comment]
Same thing with Brave.

**Comment by cuiko** [comment]
> Try:
> 
> ```
> yabai -m rule --add title="^Picture in Picture$" manage=off mouse_follows_focus=off
> ```
> 
> I solved my PiP issues in Chromium this way

thank for your inspiration, i fix it by following.
```bash
yabai -m rule --add subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off
```

**Comment by natelook** [comment]
> ```shell
> yabai -m rule --add subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off
> ```

This fixed for me too

**Comment by ditadi** [comment]
Same issue, @cuiko and @natelook you guys just add this rule on yabai config file?

I tried but the same issue happens, when I change with a video the focus returns to arc, or when I click to pause the pip video on arc, the focus goes to arc also.

This is killing the yabai experience for me.

**Comment by Khodaparastan** [comment]
I have the same problem but `yabai -m rule --add subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off` made a minor difference for me 
I have to select another tab in arc so that the pip windows gets created and then change workspace
before adding this to config whenever I hovered my curser on the pip windows it would go the to arc window but now I doesn't 
but still whenever I'm on a youtube video and want change window or workspace it jump to the arc windows without selecting another tab first

**Comment by corruptmane** [comment]
> but still whenever I'm on a youtube video and want change window or workspace it jump to the arc windows without selecting another tab first

have you fixed this? I have exactly the same issue and don't know what to do about it

**Comment by koekeishiya** [comment]
Should be resolved in latest version.

**Comment by alankritjoshi** [comment]
I still see this issue, even after adding the exception for `AXSystemDialog` to config at the end and restarting yabai. The mouse jumps to a different place.

I don't see this issue if my global setting for `mouse_follows_focus` is `off`

`yabai -m config mouse_follows_focus          off`

**Comment by cuiko** [comment]
I try to comment the related rule, The issue will recur(when I click the PIP window, the mouse will move to left-bottom).

> `yabai -m rule --add app="^(Arc)$" subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off`

But when I reuse the rule, the issue solved.

Here is my shortened config.
```shell
apps=$(awk -v ORS='|' '{if($0!="") print $0}' $XDG_CONFIG_HOME/yabai/yabaimanaged)
yabai -m rule --add app!="^${apps%?}$" manage=off
yabai -m rule --add app="^(Arc)$" subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off
```

**Comment by MattressPadley** [comment]
I am also still experiencing this issue. I've tried all the configs listed above and at time it has seemingly worked properly but now not at all. it can be fixed by setting

`yabai -m config mouse_follows_focus on`

**Comment by weeebdev** [comment]
Now there is another problem, I cannot use Command+Tab to switch between the spaces when PiP is active. It always jumps back to the current space.

**Comment by MattressPadley** [comment]
Experiencing this issue on current version. when clicking on arc pip mouse moves to bottom left corner of screen. After clicking once I can then move the pip as normal so long as I don't either leave the screen and come back or focus another window.

**Comment by armangurkan** [comment]
I am having a similar issue with microsoft teams in multi monitor.  when I screen share axsystemdialog windows come up for the frame that indicates the shared window and annotation menu, and when ever I want to switch display and move focus to the display that is being shared, it moves back to the display where the main microsoft teams app is instead of moving east or west.  Did anybody experience this issue?  Please let me know.

**Comment by cuiko** [comment]
> I am having a similar issue with microsoft teams in multi monitor. when I screen share axsystemdialog windows come up for the frame that indicates the shared window and annotation menu, and when ever I want to switch display and move focus to the display that is being shared, it moves back to the display where the main microsoft teams app is instead of moving east or west. Did anybody experience this issue? Please let me know.我在多显示器中使用 Microsoft Teams 时遇到了类似的问题。当我屏幕共享 axsystemdialog 窗口出现指示共享窗口和注释菜单的框架时，当我想切换显示并将焦点移动到正在共享的显示器时，它会移回主 Microsoft Teams 应用程序所在的显示器，而不是向东或向西移动。有人遇到过这个问题吗？请告诉我。

Same with you in this case of multiple display. I have to close axsystemdialog to switch display.

**Comment by ViaxCo** [comment]
> I still see this issue, even after adding the exception for `AXSystemDialog` to config at the end and restarting yabai. The mouse jumps to a different place.
> 
> I don't see this issue if my global setting for `mouse_follows_focus` is `off`
> 
> `yabai -m config mouse_follows_focus off`

This fixed it for me too. That's unfortunate. I really love `mouse_follows_focus`.

**Comment by ckreiling** [comment]
Also experiencing the same issue with mouse moving to bottom screen. Only way is to turn off global `mouse_follows_focus`.

My current workaround, which is unideal but workable, is the following:

```
yabai -m signal --add event=window_focused app="Arc" title="^$" \
  action="yabai -m config mouse_follows_focus off && sleep 10 && yabai -m config mouse_follows_focus on"
```

When focusing the floating window (`app="Arc" title="^$"`) by clicking on it, turn off mouse_follows_focus, sleep for 10 seconds, and then turn it back on.

alternatively if using skhd, setting up keybindings for toggling mouse_follows_focus:

```
# .skhdrc
shift + alt - m : yabai -m mouse_follows_focus off
ctrl + alt -m : yabai -m mouse_follows_focus on
```

**Comment by ericwang401** [comment]
Please see [my comment here](https://github.com/asmvik/yabai/issues/2419#issuecomment-4715150007) if you are looking for a solution
