### ISSUE TITLE
`yabai -m space --focus x` didn't work for macOS Sonoma 14.1

### ISSUE THREAD

**Issue by Linghan-z** [koekeishiya/yabai#1956]
yabai v6.0.0
 this problem occurs after I upgraded my macos to Sonoma...

input: `yabai -m space --focus 1`  and nothing happend

**Comment by Linghan-z** [comment]
> @Linghan-z dup #1936

thanks! now I know it's not my problem

**Comment by juliends** [comment]
This issue is solved if you install [Yabai from HEAD](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD))
The last [commit](https://github.com/koekeishiya/yabai/commit/2c4e397e8dabc3720c17a68258677fc3e0937a61) fixes it

**Comment by Linghan-z** [comment]
> This issue is solved if you install [Yabai from HEAD](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)) The last [commit](https://github.com/koekeishiya/yabai/commit/2c4e397e8dabc3720c17a68258677fc3e0937a61) fixes it

thanks a lot!!

**Comment by OfficialCRUGG** [comment]
> This issue is solved if you install [Yabai from HEAD](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)) The last [commit](https://github.com/koekeishiya/yabai/commit/2c4e397e8dabc3720c17a68258677fc3e0937a61) fixes it

I'm now on 6.0.1 which includes this commit, but I still can't get it to work.
`yabai -m space --focus 2` no output, no space switch. When I then do `yabai -m space --focus 1` again it just says "cannot focus an already focused space."

**Comment by Try431** [comment]
> > This issue is solved if you install [Yabai from HEAD](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)) The last [commit](https://github.com/koekeishiya/yabai/commit/2c4e397e8dabc3720c17a68258677fc3e0937a61) fixes it
> 
> I'm now on 6.0.1 which includes this commit, but I still can't get it to work. `yabai -m space --focus 2` no output, no space switch. When I then do `yabai -m space --focus 1` again it just says "cannot focus an already focused space."

Same here, I'm on Sonoma 14.2 and am having the same issues.

**Comment by wangrunlin** [comment]
> > This issue is solved if you install [Yabai from HEAD](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)) The last [commit](https://github.com/koekeishiya/yabai/commit/2c4e397e8dabc3720c17a68258677fc3e0937a61) fixes it
> 
> I'm now on 6.0.1 which includes this commit, but I still can't get it to work. `yabai -m space --focus 2` no output, no space switch. When I then do `yabai -m space --focus 1` again it just says "cannot focus an already focused space."

Same here, Sonoma 14.2.1, yabai 6.0.2

**Comment by Vanderhoof** [comment]
For me it fixed after updating yabai from 6.0.1 to 6.0.2 (just a regular version from homebrew), Sonoma 14.2.1

**Comment by wangrunlin** [comment]
> > > This issue is solved if you install [Yabai from HEAD](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)) The last [commit](https://github.com/koekeishiya/yabai/commit/2c4e397e8dabc3720c17a68258677fc3e0937a61) fixes it
> > 
> > 
> > I'm now on 6.0.1 which includes this commit, but I still can't get it to work. `yabai -m space --focus 2` no output, no space switch. When I then do `yabai -m space --focus 1` again it just says "cannot focus an already focused space."
> 
> Same here, Sonoma 14.2.1, yabai 6.0.2

After updating Yabai, I encountered success by adjusting the configuration hash value.
https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
