### ISSUE TITLE
Not managing wezterm-gui until after restarting yabai

### ISSUE THREAD

**Issue by khaneliman** [koekeishiya/yabai#2190]
After 7.0 (I think) I started noticing wezterm-gui from nixpkgs doesn't get managed until I restart yabai. If i launch wezterm while yabai is running it gets ignored from being tiled, for some reason. 

EDIT: Played around with launching the .App instead of directly invoking the binary. When I launch the .App it is managed, i can then invoke the binary and see it managed if the .App is still running. But, launching the wezterm-gui binary itself seems to be ignored. 

<details>
<summary> before: </summary>
<img width="1473" alt="Screenshot 2024-03-27 at 3 51 18 PM" src="https://github.com/koekeishiya/yabai/assets/1778670/f5c9d3a8-dcf0-4297-911c-005a7be24e9f">
</details>

<details>
<summary> after: </summary>
<img width="778" alt="Screenshot 2024-03-27 at 3 51 43 PM" src="https://github.com/koekeishiya/yabai/assets/1778670/ba937608-3065-418c-9fa6-6ee92cf8553e">
</details>

**Comment by koekeishiya** [comment]
Sounds like same issue as https://github.com/koekeishiya/yabai/issues/2168

**Comment by koekeishiya** [comment]
Whitelisted on master.

**Comment by koekeishiya** [comment]
Changed how this works. Explicit whitelisting should no longer be necessary.

**Comment by koekeishiya** [comment]
Should be fixed in v7.0.4.

**Comment by khaneliman** [comment]
Thanks, just updated to 7.0.4 and it works again. Appreciate it, @koekeishiya

**Comment by GameFuzzy** [comment]
I'm still experiencing this issue running the latest commit (since 82727a2), both with zathura and wezterm-gui, though it only seems to occur about 50% of the time.

**Comment by rcorre** [comment]
Same, I'm on `yabai-v7.1.1`, and wezterm is sometimes managed, sometimes not.

**Comment by GameFuzzy** [comment]
@koekeishiya could you please reopen this issue?

**Comment by 3bbbeau** [comment]
It's not a permanent solution perhaps, but I realized this happened on both `yabai` and `komorebi` when I disabled the title bar in WezTerm during the initial configuration (which most people do with tiling WMs).

I made a compromise by setting:

```lua
config.window_decorations = "INTEGRATED_BUTTONS|RESIZE"
```

I tried it with on both Windows and macOS which resolved the problem for me, and it still looks nice for me with tabs. So perhaps something to do with Wezterm and how disabling the title bar exposes the handle within the OS API.

**Comment by GameFuzzy** [comment]
> It's not a permanent solution perhaps, but I realized this happened on both `yabai` and `komorebi` when I disabled the title bar in WezTerm during the initial configuration (which most people do with tiling WMs).
> 
> I made a compromise by setting:
> 
> ```lua
> config.window_decorations = "INTEGRATED_BUTTONS|RESIZE"
> ```
> 
> I tried it with both Windows and macOS which resolved the problem for me, and it still looks nice for me with tabs. So perhaps something to do with Wezterm and how disabling the title bar exposes the handle within the OS API.

Didn't fix the issue on my end.

**Comment by escwxyz** [comment]
Issue persists with yabai v7.1.2

**Comment by AlJohri** [comment]
I'm also running into the same issue. I just reported it upstream to wezterm here: https://github.com/wez/wezterm/issues/6075

**Comment by escwxyz** [comment]
> I'm also running into the same issue. I just reported it upstream to wezterm here: https://github.com/wez/wezterm/issues/6075

Make sure to re-run the script injection. 

That's how I solved the issue.

**Comment by AlJohri** [comment]
>Make sure to re-run the script injection.

@escwxyz Are you suggesting to re-run `sudo yabai --load-sa`? That didn't work for me. However, `yabai --restart-service` did indeed fix it although that's not a long term solution.

https://github.com/user-attachments/assets/d92aed7d-2584-4f04-8504-5d5cb37267d5

**Comment by AlJohri** [comment]
>I made a compromise by setting:
>
>config.window_decorations = "INTEGRATED_BUTTONS|RESIZE"

FWIW, this also did not work for me.

Note, the issue only occurs for me when I run `wezterm` via the CLI.

**Comment by AlJohri** [comment]
Found a workaround! Following the advice [here](https://github.com/koekeishiya/yabai/issues/1250#issuecomment-1157252933) for alacritty, If I run wezterm via the CLI like this it seems to work properly:

```
/Applications/WezTerm.app/Contents/MacOS/wezterm
```

**Comment by Avishayy** [comment]
For what it's worth, I'm having the same issue, and unless window_decorations are set to at least INTEGRATED_BUTTONS, the window is unmanaged, I don't like having the integrated buttons on my terminal windows, so for now I'm just using fullscreen, but this does seem like an issue with yabai where it doesn't manage windows without decorations.

**Comment by sarojregmi200** [comment]
Does anyone have any solution other than, enabling window decorations?

**Comment by koekeishiya** [comment]
I don't understand what issue you are having.. I can open wezterm directly from a terminal, or using the app bundle, with `window_decorations = "RESIZE".

![wezterm](https://github.com/user-attachments/assets/12fff9a9-4f77-49c7-abd7-0fc80e61c998)

**Comment by distek** [comment]
Posting this as I appear to have this working now without issue.

In skhd, this works to launch a managed wezterm window:
```
cmd - return : command /Applications/WezTerm.app/Contents/MacOS/wezterm-gui start --always-new-process
```

Before, I was doing this which was only working after restarting yabai:
```
cmd - return : command /Applications/WezTerm.app/Contents/MacOS/wezterm --always-new-process
```

Not sure what the difference is under the hood, but I got the hint from koekeishiya's last comment:
> to the **wezterm-gui** binary

My decorations are now just set to `RESIZE` and it's working fine.

Hope this helps!
