### ISSUE TITLE
[Support request]: Yabai not tiling windows properly after update to ver 3

### ISSUE THREAD

**Issue by BlueDrink9** [koekeishiya/yabai#524]
Yabai is making single windows take up the full screen fine, but opening new windows via skhd seems to have broken some time after updating to version 3. The second windows are opening either in the top quarter (with blank space below), or bottom quarter (blank above), or sometimes in the middle of the screen. Openign a 3rd window puts it in the blank quarter, but off-center. Running `yabai -m space --balance` with 2 windows will sometimes mode the quartered window to the center the first time, then to full half-screen the second time.
Sometimes the second window opens fine, but when I open a 3rd, the second window moves to quarter correctly, but the 3rd window opens in the same quarter, again misaligned.

This even happens if I restart with no `yabairc`. Persisting across restarts.

Downgrading back to 2.4.3 also hasn't helped.

Are there some caches I could look at clearing to help reinstall?

**Comment by koekeishiya** [comment]
> New self-signed certificate used to sign the released binaries because the previous one expired at april 21th, 2020. You will have to re-enable accessibility permissions after this install. Sorry about that.

I had to change the certificate for the 3.x.x release so you probably got hit by some accessibility nonsense. Try to first stop the yabai service, uninstall, then remove the yabai entry from the accessibility list. Do a system reboot, install yabai, and accept the accessibility permission followed by an application restart.

**Comment by BlueDrink9** [comment]
I got prompted by accessibility when I updated, and gave it permission again. And occasionally yabai does work as intended, for one window. Yabai definitely can move windows around. And I get the notification that the scriping addon loads properly.

**Comment by koekeishiya** [comment]
Yes, it should still help. The issues you describe sound very much like an inconsistency with the accessibility permission where the system sometimes think you have access, and sometimes it thinks you don't. I don't exactly know the details of why it happens, but I did experience these symptoms a long time ago when I first started doing these things.

**Comment by koekeishiya** [comment]
Closing this. My previous comment should resolve the issue for you.

**Comment by BlueDrink9** [comment]
I hadn't gotten around to restarting, but I just went through the steps you gave. Still happening, but I noticed the scripting addon gave a warning about an out-of-date payload. Small and easy thing to miss, might be worth making more obvious/documenting somewhere, or even prompting to auto-reinstall. I'm going to reinstall the scripting addon now and see if it fixes it

**Comment by BlueDrink9** [comment]
Nope, didn't work, even after multiple restarts and no yabairc. Is there anything else I can clear?

**Comment by BlueDrink9** [comment]
Spamming `balance` eventually gets the spacing right, btw, but almost always takes more than one balance (if that helps you identify possible causes)

**Comment by koekeishiya** [comment]
I have no clue. There has not been any changes related to how tiling is performed in a long time.

**Comment by BlueDrink9** [comment]
I'm not suggesting it's a bug, but does Yabai store any other settings/data that I could remove?

**Comment by koekeishiya** [comment]
There shouldn’t be, no. Accessibility access and the config file is pretty much everything. There are lock files and socket files in /tmp/yabai_<USER>.socket/lock, but that does not seem relevant to your issue.

**Comment by BlueDrink9** [comment]
Bother. Maybe I'll try on a different user and see if it's a software conflict. I'm on Mojave atm.

**Comment by BlueDrink9** [comment]
On a new user with no rc, kitty seemed to tile fine, but finder, chrome don't tile well at all.

**Comment by BlueDrink9** [comment]
Seems to be working fine again after uninstalling and re-installing the scripting addition, updating catalina, zapping the PRAM, and running manually instead of as a brew service. No idea which part fixed it. However, the scripting addition isn't loading, but I definitely ran `csrutil enable --without debug --without fs` in recovery mode. Currently, (and immediately after that command) `csrutil status` returns `enabled`, but I assume that's the expected behaviour for OSX 10.14 and above?

**Comment by BlueDrink9** [comment]
Although now windows are tiling veery slowly (iterating size and position about once every 0.5 seconds). Any thoughts on what might be causing that?

**Comment by koekeishiya** [comment]
Is this on v3.1.1 or the master branch? If so, likely fixes to #16 … god damnit

**Comment by BlueDrink9** [comment]
3.1.1

**Comment by koekeishiya** [comment]
Try the latest version please. I undid the changes to #16. Hoping that was the issue, otherwise I am running empty on ideas.

**Comment by BlueDrink9** [comment]
Yup, back to normal speed. Thank you for your help and work!

All of this stopping and restarting yabai has narrowed it down as a factor in a more serious issue I have been having (since version 3.10). Switching to new windows sometimes crashes windowserver (manifesting as a black screen, then the login screen shows). Focussing the system preferences window for the first time as it opens seems to be a factor, but if it is opened without yabai running then switched to once yabai has started, it seems to be fine.

I'll test with a minimal rc and see if it keeps happening.

**Comment by BlueDrink9** [comment]
Update: 3.1.12 seems to have reverted my issue with windows not tiling properly.

**Comment by koekeishiya** [comment]
The crash is likely #277
You need to set window_opacity_duration to 0 (macOS Catalina bug, nothing I can do to fix it).

I find it weird that going from 3.1.1 to 3.1.2 make things not tile properly. All I changed was remove a potential bug that could result in looped movement/resize.

Do you have this issue for specific applications or all of them? What about Terminal.app or Safari? (both of these work perfectly for me).

Sent from my iPhone

On 9 Jun 2020, at 01:35, BlueDrink9 <notifications@github.com> wrote:

﻿

Update: 3.1.12 seems to have reverted my issue with windows not tiling properly.

**Comment by BlueDrink9** [comment]
Maybe 3.1.1 didn't fix the bug, but it seemed to for the brief period of time I used it.

Thanks for pointing out 277. For some reason googling "yabai" + "crash" or "black screen" or "windowserver crash" didn't bring it up.

I've been testing with finder, chrome and kitty. I'll test with terminal and safari.

**Comment by BlueDrink9** [comment]
Safari and terminal were both fine. I wonder if it has to do with finder, chrome and kitty all being started by skhd (which in turn was started by yabai)

**Comment by BlueDrink9** [comment]
I got fed up with this again so went on a deep dive fixing things. New user with most things copied = worked. My user with `~/Library` renamed = worked.

I think now it is finally fixed, thanks to deleting a bunch of folders in `~/Library/application support/com.apple.*`, mostly to do with accessibility (I think `com.apple.TCC` was the main one). Complete list:

```
com.apple.CommerceKit.AskPermissionExtension
com.apple.cloudphotosd
com.apple.CloudPhotosConfiguration
com.apple.CloudDocsDaemon.StorageManagement
com.apple.CloudDocs.MobileDocumentsFileProvider
com.apple.ClassKit.diagnosticextension
com.apple.calculator
com.apple.BKAgentService
com.apple.AuthKitUI.AKFollowUpServerUIExtension
com.apple.AuthKitUI.AKAppSSOExtension
com.apple.archiveutility
com.apple.AquaAppearanceHelper
com.apple.AppStoreDaemon.ASDAskPermissionExtension
com.apple.AppSSOKerberos.KerberosExtension
com.apple.AppleMediaServicesUI.SpyglassPurchases
com.apple.AppleMediaServices.FollowUpExtension
com.apple.appkit.xpc.LegacyExternalColorPickerService
com.apple.appkit.xpc.ColorSampler
com.apple.AMPDeviceDiscoveryAgent
com.apple.AMPArtworkAgent
com.apple.amp.devicesui
com.apple.AmbientDisplayAgent
com.apple.AirPlayUIAgent
com.apple.AddressBook.UrlForwarder
com.apple.AddressBook.ContactsAccountsService
com.apple.AddressBook.ABPersonViewService
com.apple.AddressBook
com.apple.accessibility.mediaaccessibilityd
com.apple.accessibility.heard
com.apple..NowPlayingWidgetContainer.NowPlayingWidget
com.apple..NowPlayingWidgetContainer
com.apple.AMPLibraryAgent
com.apple.backgroundtaskmanagementagent
com.apple.TCC
```

**Comment by BlueDrink9** [comment]
Happened again after a recent restart. Just removing `com.apple.TCC` and logging out didn't fix it, but removing `com.apple.*` and logging out did.

**Comment by BlueDrink9** [comment]
I have identified the cause of this as a clash with a Hammerspoon script.
Removing the above files affected hammerspoon being set or not set to auto-open on login.

Running with just hammerspoon was fine, but when loading dbalatero/VimMode.spoon and reloading the config, this issue occurs again.
I have opened https://github.com/dbalatero/VimMode.spoon/issues/45 to hopefully shed some light on this.
