### ISSUE TITLE
cannot focus space due to an error with the scripting-addition

### ISSUE THREAD

**Issue by rmGFW** [koekeishiya/yabai#787]
macOS version 11.1

`csrutil status`  output  is  `System Integrity Protection status: disabled`

already tried reinstall scripting-addition `sudo yabai --uninstall-sa && sudo yabai --install-sa`

**Comment by rmGFW** [comment]
yabai-v3.3.6

**Comment by yanzhang0219** [comment]
After `sudo yabai --install-sa`, did you run `sudo yabai --load-sa` manually? If not, try to run it.

**Comment by rmGFW** [comment]
thanks ! it works ! 👍

**Comment by yanzhang0219** [comment]
@koekeishiya Will you consider to mention this (manually run `sudu yabai --load-sa`) in the wiki? I saw many users have such a concern.  In the first installation, sometimes `sudo yabai --install-sa` won't load sa automatically. 
Thanks.

**Comment by koekeishiya** [comment]
This is actually mentioned in the wiki already: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup

**Comment by yanzhang0219** [comment]
Yeah, it just mentions that scripting-addtion is not loaded automatically on startup. What I mean is that it is not loaded on the first installation either. So after installation of yabai, we should first run `sudo yabai --load-sa` to load sa. Then the second thing is add it at the top of yabairc to make it being loaded on each startup.

**Comment by koekeishiya** [comment]
Updated wiki.

**Comment by mihnsen** [comment]
Happened on MacOS BigSur 11.6. Already tried
`sudo yabai --uninstall-sa && sudo yabai --install-sa && sudu yabai --load-sa`

**Comment by SichangHe** [comment]
### scripting-addition failed to inject
```shell
$ yabai -m space --focus next
cannot focus space due to an error with the scripting-addition.
$ sudo yabai --load-sa 
Password:
yabai: scripting-addition failed to inject payload into Dock.app!
```
yabai-v4.0.0
macOS 12.01
M1 apple silicon

SIP is disabled

**Comment by alephpt** [comment]
same problem ^ but on Monterey 12.2

**Comment by rublev** [comment]
> same problem ^ but on Monterey 12.2

same here D: wish i could downgrade. did it work for u on 12.1? amethyst also broken on 12.2

**Comment by SichangHe** [comment]
opened a **new issue** #1158 on this problem

**Comment by usmajeed** [comment]
I'm getting "cannot focus space due to an error with the scripting-addition" on Ventura.

**Comment by palteksolution** [comment]
> I'm getting "cannot focus space due to an error with the scripting-addition" on Ventura.

Same with me on Ventura.

**Comment by dsorenes** [comment]
> > I'm getting "cannot focus space due to an error with the scripting-addition" on Ventura.
> 
> Same with me on Ventura.

It's fixed in the development version. https://github.com/koekeishiya/yabai/commit/206c0d6968210f48363f206526760e5750810a61 with https://github.com/koekeishiya/yabai/issues/1297 as context.

You can install the development version by following the wiki. https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD). You'll be asked by homebrew to unlink the previous yabai, but after that and following the instructions on the wiki it works like a charm again. Don't forget to update the `sha256` for the new binary.

**Comment by rkshthrmsh** [comment]
Still seeing this issue on Ventura 13.2.1: `yabai-v5.0.2` & SIP disabled (only need the ability to focus spaces that are created manually).

- Created `yabai-cert` as per instructions in the wiki
- Used brew to install from HEAD
- Could NOT find yabai installed in `/usr/local/bin` as per the wiki instructions. Codesigned yabai here instead:
```
> codesign -fs 'yabai-cert' /opt/homebrew/bin/yabai
> codesign -fs 'yabai-cert' /opt/brew/Cellar/yabai/HEAD-147b356/bin/yabai
``` 
- Provided accessibility permission to the executables at `/opt/brew/bin/yabai/` and `/opt/brew/Cellar/yabai/HEAD-147b356/bin/yabai` since there was nothing in the local bin.

Issue:
```
> yabai -m space --focus next   
cannot focus space due to an error with the scripting-addition.
```


Is there anything wrong here, or something else that I can try? Please let me know.

**Comment by virtu** [comment]
Problem prevails for me as well. Using latest yabai from homebrew on Ventura 13.2.1 (22D68):

```
% yabai --version
yabai-v5.0.2
% yabai -m space --focus next
yabai --cannot focus space due to an error with the scripting-addition.
```

**Comment by b0lle** [comment]
I am facing the same issue:
```
yabai -m space --focus next                                08:48:42
cannot focus space due to an error with the scripting-addition.
```

Apple Silicon
Ventura 13.5
yabai-v5.0.6 (installed from brew)
SIP status:
```
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: disabled
	BaseSystem Verification: enabled
	Boot-arg Restrictions: disabled
	Kernel Integrity Protections: enabled
	Authenticated Root Requirement: enabled
```

**Comment by now-ing** [comment]
> I am facing the same issue:我面临着同样的问题：
> 
> ```
> yabai -m space --focus next                                08:48:42
> cannot focus space due to an error with the scripting-addition.
> ```
> 
> Apple Silicon 苹果硅 Ventura 13.5  文图拉13.5 yabai-v5.0.6 (installed from brew) yabai-v5.0.6（从brew安装） SIP status:  SIP 状态：
> 
> ```
> System Integrity Protection status: unknown (Custom Configuration).
> 
> Configuration:
> 	Apple Internal: disabled
> 	Kext Signing: enabled
> 	Filesystem Protections: disabled
> 	Debugging Restrictions: disabled
> 	DTrace Restrictions: enabled
> 	NVRAM Protections: disabled
> 	BaseSystem Verification: enabled
> 	Boot-arg Restrictions: disabled
> 	Kernel Integrity Protections: enabled
> 	Authenticated Root Requirement: enabled
> ```

may be you should use
`
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
`

in https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition says

**Comment by dandehavilland** [comment]
> Don't forget to update the `sha256` for the new binary.

This solved it for me: updating the sha256 hash in the sudoers file for `yabai` to match the latest installed binary.

https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

**Comment by b0lle** [comment]
> > I am facing the same issue:我面临着同样的问题：
> > ```
> > yabai -m space --focus next                                08:48:42
> > cannot focus space due to an error with the scripting-addition.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Apple Silicon 苹果硅 Ventura 13.5  文图拉13.5 yabai-v5.0.6 (installed from brew) yabai-v5.0.6（从brew安装） SIP status:  SIP 状态：
> > ```
> > System Integrity Protection status: unknown (Custom Configuration).
> > 
> > Configuration:
> > 	Apple Internal: disabled
> > 	Kext Signing: enabled
> > 	Filesystem Protections: disabled
> > 	Debugging Restrictions: disabled
> > 	DTrace Restrictions: enabled
> > 	NVRAM Protections: disabled
> > 	BaseSystem Verification: enabled
> > 	Boot-arg Restrictions: disabled
> > 	Kernel Integrity Protections: enabled
> > 	Authenticated Root Requirement: enabled
> > ```
> 
> may be you should use `yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa" sudo yabai --load-sa`
> 
> in https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition says

you were right, I missed that section. Thank you!

**Comment by CalderWhite** [comment]
Anyone else getting: `sudo yabai --install-sa` ?

**Comment by CalderWhite** [comment]
Anyone else getting:
```
$ sudo yabai --install-sa
yabai: '--install-sa' is not a valid option!
```

**Comment by CalderWhite** [comment]
For anyone who comes along, try running `sudo yabai --load-sa`. For later versions of macOS this should work.

**Comment by milesromeno** [comment]
I encountered this error after running a `brew upgrade`. Re-checking the output of `shasum -a 256 $(which yabai)` showed that a new sha256 hash had been generated. Updating `/private/etc/sudoers.d/yabai` to replace the old sha256 with it fixed this.

**Comment by yourzbuddha** [comment]
> I encountered this error after running a `brew upgrade`. Re-checking the output of `shasum -a 256 $(which yabai)` showed that a new sha256 hash had been generated. Updating `/private/etc/sudoers.d/yabai` to replace the old sha256 with it fixed this.

Should this case be also listed in the wiki?

**Comment by onezhaoyn** [comment]
> I encountered this error after running a `brew upgrade`. Re-checking the output of `shasum -a 256 $(which yabai)` showed that a new sha256 hash had been generated. Updating `/private/etc/sudoers.d/yabai` to replace the old sha256 with it fixed this.

Please add this in wiki, took me hours to find this...

**Comment by b0lle** [comment]
its mentioned in the shell comments of https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
```
#   this hash must be updated manually after upgrading yabai.
```

**Comment by arbitrarily** [comment]
> Anyone else getting:
> 
> ```
> $ sudo yabai --install-sa
> yabai: '--install-sa' is not a valid option!
> ```

`sudo yabai --install-service`

**Comment by unsecretised** [comment]
> > Anyone else getting:
> > ```
> > $ sudo yabai --install-sa
> > yabai: '--install-sa' is not a valid option!
> > ```
> 
> `sudo yabai --install-service`

I did `sudo yabai --install-service` and it still doesn't work... Updated the hash as well, and tried running `sudo yabai --install-sa ` but it gives me the `yabai: --install-sa is not a valid option`

Tried doing so many things already and yet its still not working, always giving me error with scripting edition... On OS: macOS Sequoia 15.5 arm64
and M2 air chip

Edit: Got it to work, had to re-enable SIP, turns out restarting your mac disables it 😭
