### ISSUE TITLE
Payload doesn't support this Mac version

### ISSUE THREAD

**Issue by TimWSpence** [koekeishiya/yabai#911]
I started getting this error today.

I'm on Catalina 10.15.7. 

The yabai logs have
```
yabai: scripting-addition either failed to load or could not inject payload into Dock.app! Error: -1708
yabai: could not access accessibility features! abort..
yabai: could not access accessibility features! abort..
```

Yabai has accessibility privileges enabled in security preferences.

```
csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled
```

Let me know what else I can provide to aid diagnosis. Any assistance is much appreciated - I completely rely on Yabai for my workflow!

**Comment by TimWSpence** [comment]
I've managed to convince IT support to let me upgrade to Big Sur and that has thankfully fixed the problem so I guess we can close this as not reproducible?

Many thanks for all your hard work - MacOS is literally unusable for me now without Yabai 😍

**Comment by zms** [comment]
3.3.9 broke the add-on for Catalina 10.15.7 for me as well.  Running `--install-sa` gives me:

```
payload (0x2A) doesn't support this macOS version!
```

CSR is disabled.

I installed 3.3.9 with homebrew. Is there a way to downgrade without borking _everything_?

**Comment by koekeishiya** [comment]
There has not been any changes to the Catalina compatibility part for at least 6months or so. Did Apple release a supplementary update? Anyway, upload your Dock.app and I can fix it.

Sent from my iPhone

On 26 May 2021, at 14:23, Manish ***@***.***> wrote:

﻿

3.3.9 broke the add-on for Catalina 10.15.7 for me as well. Running --install-sa gives me:

payload (0x2A) doesn't support this macOS version!


CSR is disabled.

I installed 3.3.9 with homebrew. Is there a way to downgrade without borking everything?

**Comment by audreymgu** [comment]
Just chiming in here to say that Yabai broke for me after the latest security update on 10.15.7; it was working just fine prior to this.

**Comment by audreymgu** [comment]
Attaching my Dock.app with Yabai currently installed (3.3.8, haven't updated to 3.3.9). Let me know if you need me to re-upload with a different configuration!

[Dock_10.15.7_post-security-update.zip](https://github.com/koekeishiya/yabai/files/6547643/Dock_10.15.7_post-security-update.zip)

**Comment by TimWSpence** [comment]
> Just chiming in here to say that Yabai (3.3.8) broke for me after the latest security update on 10.15.7; it was working just fine prior to this.
> 
> I'm able to install the add-on, but I'm notified that the payload doesn't support this macOS version every time it launches.
> 
> SIP remains custom in exact config of OP, accesibility enabled via System Preferences.

I was on 3.3.8 as well. Sorry, forgot to specify this on the original description

**Comment by koekeishiya** [comment]
Should be fixed in v3.3.10.

**Comment by timlkelly** [comment]
Confirmed the scripting addition in v3.3.10 works on macOS 10.15.7. Thanks for the quick fix!

**Comment by zms** [comment]
Looks like for me either SKHD or Karabiner or both are still broken but that's a different problem.  Scripting addon/paylod (`v1.0.31`) with yabai 3.3.10 works on my fully patched 10.15.7.  Thank you!

**Comment by audreymgu** [comment]
Can confirm that v3.3.10 fixed the issue for me! Many thanks 🙏

**Comment by arisolt** [comment]
I'm having the same issue, but different error code:
```
payload (0x0) doesn't support this macOS version!
```

I'm already on v3.3.10. OS is Mojave 10.14.1. 

Is there something I can do to fix it?

**Comment by koekeishiya** [comment]
Upgrade to Mojave 10.14.6

**Comment by arisolt** [comment]
> Upgrade to Mojave 10.14.6

Ah, thanks. Unfortunately, I don't have that option, because macOS 10.14.1 is the last version that is compatible with an old filesystem called MacOS Extended Journaled. 

Is there an earlier version of yabai I could downgrade to, for the script additions to work?

**Comment by koekeishiya** [comment]
Unfortunately no. 10.14.4 is the earliest version of Mojave that is supported

**Comment by milksense** [comment]
`15.4 Beta (24E5206s)` not supported.

`payload (0x2A) doesn't support this macOS version!`

@koekeishiya

**Comment by mactunechy** [comment]
> `15.4 Beta (24E5206s)` not supported.
> 
> `payload (0x2A) doesn't support this macOS version!`
> 
> [@koekeishiya](https://github.com/koekeishiya)

Having a similar issue, I just upgraded to `Sequoia 15.4` and getting this:-
`payload (0x3E) doesn't support this macOS version!`

**Comment by lo-joe** [comment]
Thanks for all your work! MacOS is pleasant because of Yabai.

I got hit with the same issue on Sequoia 15.4.1 - I uninstalled, pulled the latest, and while my brew's list of my version didn't change (stayed `7.1.1`), the commit hash did update. So yeah, tip to others, follow the updating to latest release here: [updating-to-the-latest-release](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#updating-to-the-latest-release)

```shell
$ brew list koekeishiya/formulae/yabai --versions
> HEAD-41fc52b

# ...updated to latest release
> HEAD-1f525fc

yabai --version
yabai-v7.1.14
```
